<?php
/**
 * ==============================================================================
 * Automated Authoritative DNS Zone Engine (Bind9 Manager)
 * Platform: hoster1280.shop
 * ==============================================================================
 */

class DnsZoneManager
{
    private string $zonesDir;
    private string $namedLocalConf;
    private string $ns1;
    private string $ns2;
    private ?string $serverIp;

    public function __construct(
        string $zonesDir = '/etc/bind/zones',
        string $namedLocalConf = '/etc/bind/named.conf.local',
        string $ns1 = 'ns1.hoster1280.shop',
        string $ns2 = 'ns2.hoster1280.shop',
        ?string $serverIp = null
    ) {
        $this->zonesDir = $zonesDir;
        $this->namedLocalConf = $namedLocalConf;
        $this->ns1 = rtrim($ns1, '.');
        $this->ns2 = rtrim($ns2, '.');
        $this->serverIp = $serverIp ?? $this->detectServerIp();
    }

    /**
     * Detect public IPv4 dynamically
     */
    public function detectServerIp(): string
    {
        static $cached = null;
        if ($cached) return $cached;

        $sources = [
            'https://api.ipify.org',
            'https://ifconfig.me/ip',
            'https://icanhazip.com'
        ];

        foreach ($sources as $url) {
            $ctx = stream_context_create(['http' => ['timeout' => 2]]);
            $res = @file_get_contents($url, false, $ctx);
            if ($res && filter_var(trim($res), FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
                $cached = trim($res);
                return $cached;
            }
        }

        $cached = $_SERVER['SERVER_ADDR'] ?? gethostbyname(gethostname());
        return $cached;
    }

    /**
     * Create or update authoritative zone for a client domain
     */
    public function createZone(string $domain, ?string $targetIp = null, array $customRecords = []): array
    {
        $domain = strtolower(trim($domain));
        if (!preg_match('/^([a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/', $domain)) {
            return ['success' => false, 'error' => "Invalid domain syntax: {$domain}"];
        }

        $ip = $targetIp ?? $this->serverIp;
        $serial = date('Ymd01');
        $zoneFile = "{$this->zonesDir}/db.{$domain}";

        // Ensure zones directory exists
        if (!is_dir($this->zonesDir)) {
            @mkdir($this->zonesDir, 0755, true);
        }

        // Build standard RFC-compliant Bind9 Zone content
        $zoneContent = <<<EOF
; ==============================================================================
; Authoritative DNS Zone for: {$domain}
; Generated by hoster1280.shop DNS Engine
; ==============================================================================
\$TTL    86400
@       IN      SOA     {$this->ns1}. hostmaster.{$this->ns1}. (
                              {$serial} ; Serial
                              7200         ; Refresh (2h)
                              3600         ; Retry (1h)
                              1209600      ; Expire (2w)
                              86400 )      ; Minimum TTL (1d)
;
; Authoritative Nameservers
@       IN      NS      {$this->ns1}.
@       IN      NS      {$this->ns2}.

; Primary Host Records
@       IN      A       {$ip}
www     IN      A       {$ip}
cpanel  IN      A       {$ip}
ftp     IN      A       {$ip}
mail    IN      A       {$ip}

; Mail Exchange (MX) & SPF TXT Records
@       IN      MX  10  mail.{$domain}.
@       IN      TXT     "v=spf1 a mx ip4:{$ip} ~all"

EOF;

        // Append custom records if provided
        foreach ($customRecords as $r) {
            $name = $r['name'] ?? '@';
            $type = strtoupper($r['type'] ?? 'A');
            $val = $r['value'] ?? $ip;
            $ttl = $r['ttl'] ?? 14400;
            $zoneContent .= sprintf("%-8s IN %-5s %-7s %s\n", $name, "{$ttl}", $type, $val);
        }

        // Write zone file
        $written = @file_put_contents($zoneFile, $zoneContent);
        if ($written === false) {
            // Attempt with sudo if running under standard web user
            $tmpFile = "/tmp/db.{$domain}." . time();
            file_put_contents($tmpFile, $zoneContent);
            shell_exec("sudo cp {$tmpFile} {$zoneFile} && sudo rm -f {$tmpFile}");
        }

        // Set ownership & permissions
        @chown($zoneFile, 'bind');
        @chmod($zoneFile, 0644);

        // Register zone in named.conf.local
        $this->registerZoneInLocalConf($domain, $zoneFile);

        // Validate syntax with named-checkzone
        $checkCmd = sprintf('named-checkzone %s %s 2>&1', escapeshellarg($domain), escapeshellarg($zoneFile));
        $checkOut = shell_exec($checkCmd);

        // Reload Bind9 gracefully
        $this->reloadBind($domain);

        return [
            'success' => true,
            'domain' => $domain,
            'zoneFile' => $zoneFile,
            'ip' => $ip,
            'serial' => $serial,
            'nameservers' => [$this->ns1, $this->ns2],
            'validation' => trim((string)$checkOut)
        ];
    }

    /**
     * Remove zone file and entry from named.conf.local
     */
    public function deleteZone(string $domain): array
    {
        $domain = strtolower(trim($domain));
        $zoneFile = "{$this->zonesDir}/db.{$domain}";

        if (file_exists($zoneFile)) {
            @unlink($zoneFile);
            shell_exec("sudo rm -f " . escapeshellarg($zoneFile));
        }

        // Remove from named.conf.local
        if (file_exists($this->namedLocalConf)) {
            $content = file_get_contents($this->namedLocalConf);
            $pattern = '/zone\s+"' . preg_quote($domain, '/') . '"\s*\{[^}]*\};\s*/s';
            $newContent = preg_replace($pattern, '', $content);
            if ($newContent !== $content) {
                file_put_contents($this->namedLocalConf, $newContent);
            }
        }

        $this->reloadBind();

        return [
            'success' => true,
            'message' => "Zone {$domain} deleted successfully."
        ];
    }

    /**
     * Append zone definition to named.conf.local safely without duplicates
     */
    private function registerZoneInLocalConf(string $domain, string $zoneFile): void
    {
        if (!file_exists($this->namedLocalConf)) {
            return;
        }

        $conf = file_get_contents($this->namedLocalConf);
        if (strpos($conf, "\"{$domain}\"") !== false) {
            return; // Already registered
        }

        $zoneBlock = <<<EOF

zone "{$domain}" {
    type master;
    file "{$zoneFile}";
    allow-transfer { none; };
};
EOF;

        if (@file_put_contents($this->namedLocalConf, $zoneBlock, FILE_APPEND) === false) {
            // Sudo fallback
            $tmpFile = "/tmp/named_zone_" . time() . ".txt";
            file_put_contents($tmpFile, $zoneBlock);
            shell_exec("cat {$tmpFile} | sudo tee -a {$this->namedLocalConf} >/dev/null && rm -f {$tmpFile}");
        }
    }

    /**
     * Reload Bind9 service or specific zone via rndc
     */
    public function reloadBind(?string $domain = null): bool
    {
        if (PHP_OS_FAMILY !== 'Linux') {
            return true;
        }

        if ($domain) {
            $cmd = sprintf('sudo rndc reload %s 2>&1', escapeshellarg($domain));
            $out = shell_exec($cmd);
            if ($out && strpos($out, 'reload zones and configuration') !== false) {
                return true;
            }
        }

        // General graceful reload
        $cmd = 'sudo systemctl reload bind9 2>/dev/null || sudo systemctl reload named 2>/dev/null || true';
        shell_exec($cmd);
        return true;
    }
}

// CLI Direct Invocation Support
if (php_sapi_name() === 'cli' && isset($argv[1])) {
    $action = $argv[1];
    $domain = $argv[2] ?? '';
    $ip = $argv[3] ?? null;

    $manager = new DnsZoneManager();

    if ($action === 'create' && $domain) {
        $res = $manager->createZone($domain, $ip);
        echo json_encode($res, JSON_PRETTY_PRINT) . PHP_EOL;
    } elseif ($action === 'delete' && $domain) {
        $res = $manager->deleteZone($domain);
        echo json_encode($res, JSON_PRETTY_PRINT) . PHP_EOL;
    } elseif ($action === 'reload') {
        $manager->reloadBind($domain ?: null);
        echo json_encode(['success' => true, 'message' => 'Bind9 reloaded']) . PHP_EOL;
    } else {
        echo "Usage: php DnsZoneManager.php [create <domain> [ip]|delete <domain>|reload [domain]]\n";
    }
}
